#!/bin/bash
# Generate the documentation's reference pages from the toolchain itself.
#
# Nothing here is written by hand. A hand-copied command table is out of date
# by the next release and nobody notices until a reader tries one; asking the
# compiler what it supports is the only version that stays true.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"
OUT="$ROOT/docs-site/src"
KILN="${KILN:-$ROOT/target/release/kiln}"
[ -x "$KILN" ] || KILN="$ROOT/target/debug/kiln"
[ -x "$KILN" ] || { echo "build kiln first (cargo build)" >&2; exit 1; }

banner='<!-- Generated by tools/gen-docs.sh — do not edit; edit the toolchain. -->'

# --- commands -------------------------------------------------------------
# Every kit is documented, discovered rather than listed, so a new one appears
# here the moment it exists. The list comes from `kiln kits` rather than a
# glob over libs/ so that an installed kit is documented exactly when it is
# usable — one resolution, not a second one that drifts from it. `hello` is
# excluded: it is a worked example for library authors, not something a program
# should `use`.
LIBS=()
while read -r name _version _tier; do
    [ "$name" = "hello" ] && continue
    LIBS+=("$name")
# Sorted by name: `order` is where a kit sits in a toolbox, which is not how a
# reader looks something up in a reference.
done < <("$KILN" kits | sed -n 's/^kit: //p' | sort)

# A command's library is not in the output, so it is recovered by difference:
# what `--use X` lists that core alone does not.
"$KILN" commands | sed -n 's/^command: //p' | sort > /tmp/kiln-core-cmds.$$

# The index at the top of a library's section. The name links to that command's
# own entry below, when it has one — `emit_entries` writes the headings those
# links point at, and a command with no documentation simply has no anchor to
# reach, which is what makes the reference legible while it is half written.
emit_table() {
    local documented="$1"
    printf '| Command | Parameters | Returns |\n| --- | --- | --- |\n'
    sort | while read -r line; do
        name="${line%%(*}"
        rest="${line#*(}"
        params="${rest%%)*}"
        ret="${line##*) -> }"
        [ "$ret" = "$line" ] && ret="—"
        if grep -qxF "$name" "$documented" 2>/dev/null; then
            printf '| [`%s`](#%s) | %s | %s |\n' "$name" "$name" "${params:-—}" "$ret"
        else
            printf '| `%s` | %s | %s |\n' "$name" "${params:-—}" "$ret"
        fi
    done
}

# One entry per documented command: what it does, and a program that calls it.
#
# The example is emitted as a WHOLE program, not a fragment. Two reasons, and
# both are the point of having examples at all: `tools/check-docs.sh` compiles
# every fenced sample in these pages, so an example that is a whole program is
# an example the build proves correct; and Studio's copy button hands the
# reader something that runs, rather than three lines they have to wrap.
#
# $1 the raw `kiln commands` listing, $2 the library name ("" for core),
# $3 the file naming the commands that belong in this section.
emit_entries() {
    local listing="$1" lib="$2" own="$3"
    local name
    while read -r name; do
        grep -qxF "$name" "$own" || continue
        local doc
        doc="$(sed -n "s/^doc: $name //p" "$listing")"
        [ -n "$doc" ] || continue
        local sig
        sig="$(sed -n "s/^command: //p" "$listing" | grep "^$name(" | head -1)"
        printf '\n### `%s`\n\n' "$name"
        printf '`%s`\n\n' "$sig"
        printf '%s.\n' "$doc"
        # No example is better than a wrong one, and the heading still gives
        # the reader the signature and the sentence.
        if grep -q "^example: $name " "$listing"; then
            # Most examples are statements, and are wrapped in the module and
            # `main` a reader would have to write around them anyway. An
            # example that opens with `module` is a whole program already —
            # which is the only way to show a command whose argument needs a
            # declaration, a `record` or a component, since neither can be
            # written inside a subroutine. Such an example carries its own
            # `use`, because the wrapper is not there to add one.
            if [ "$(sed -n "s/^example: $name //p" "$listing" | head -1 | cut -c1-7)" = "module " ]; then
                printf '\n```kiln\n'
                sed -n "s/^example: $name //p" "$listing"
                printf '```\n'
            else
                printf '\n```kiln\nmodule example\n'
                [ -n "$lib" ] && printf 'use %s\n' "$lib"
                printf '\nsub main\n'
                sed -n "s/^example: $name //p" "$listing" | sed 's/^/  /'
                printf 'end\n```\n'
            fi
        fi
    done < <(sed -n 's/^doc: //p' "$listing" | cut -d' ' -f1 | sort -u)
}

{
    echo "$banner"
    echo
    cat <<'MD'
# Commands

Call one as a statement with `call`, or use its result in an expression when it
returns a value.

```
call print_text("hello")            # as a statement
let n: int = max_int(3, 9)          # as an expression
```

The core commands are always available. The rest come from a support library,
which a module asks for by name:

```
module report
use file

sub main
  call print_text(file_read_text("notes.txt"))
end
```

A command that can fail returns a sentinel — `0` for a handle or a position,
`-1` for a count or size, `""` for text, `false` for a yes/no — and leaves the
reason in the error slot, which `last_error_code()` and `last_error_text()`
read. The [Language guide](./language.md#when-a-command-fails) has the rules.

## Core

MD
    "$KILN" commands > /tmp/kiln-core-raw.$$
    sed -n 's/^doc: //p' /tmp/kiln-core-raw.$$ | cut -d' ' -f1 | sort -u \
        > /tmp/kiln-core-doc.$$
    sed -n 's/^command: //p' /tmp/kiln-core-raw.$$ | sed 's/(.*//' | sort -u \
        > /tmp/kiln-core-own.$$
    cat /tmp/kiln-core-cmds.$$ | emit_table /tmp/kiln-core-doc.$$
    emit_entries /tmp/kiln-core-raw.$$ "" /tmp/kiln-core-own.$$

    for l in "${LIBS[@]}"; do
        printf '\n## %s\n\n`use %s`\n\n' "$l" "$l"
        "$KILN" commands --use "$l" > /tmp/kiln-lib-raw.$$
        # This library's own commands: what `--use` adds that core alone lacks.
        sed -n 's/^command: //p' /tmp/kiln-lib-raw.$$ | sort |
            comm -13 /tmp/kiln-core-cmds.$$ - > /tmp/kiln-lib-cmds.$$
        sed 's/(.*//' /tmp/kiln-lib-cmds.$$ | sort -u > /tmp/kiln-lib-own.$$
        sed -n 's/^doc: //p' /tmp/kiln-lib-raw.$$ | cut -d' ' -f1 | sort -u \
            > /tmp/kiln-lib-doc.$$
        emit_table /tmp/kiln-lib-doc.$$ < /tmp/kiln-lib-cmds.$$
        emit_entries /tmp/kiln-lib-raw.$$ "$l" /tmp/kiln-lib-own.$$
    done
} > "$OUT/reference-commands.md"
rm -f /tmp/kiln-core-cmds.$$ /tmp/kiln-core-raw.$$ \
      /tmp/kiln-core-doc.$$ /tmp/kiln-core-own.$$ \
      /tmp/kiln-lib-raw.$$ /tmp/kiln-lib-cmds.$$ \
      /tmp/kiln-lib-own.$$ /tmp/kiln-lib-doc.$$

# --- components -----------------------------------------------------------
# Grouped by the library that declares them, and discovered the same way the
# command tables are. A component is no longer a `ui` thing: core ships `timer`
# and `net` ships `httpserver`, so a page built from one library's list would
# quietly omit whatever the newest one added.
{
    echo "$banner"
    echo
    cat <<'MD'
# Components

A component has properties you set and events you bind to subroutines — from
the designer, or by writing it out directly. Most draw a rectangle; some, like
`timer` and `httpserver`, have no pixels at all and are declared at module
level rather than inside a form. What each component is for, and what its
events hand a handler, is in [Components](./components.md); this page is the
list.

MD
    "$KILN" commands | sed -n 's/^component: //p' | sort > /tmp/kiln-core-comps.$$

    emit_components() {   # $1 = heading, $2… = `commands` invocation output file
        local list
        list=$(sed -n 's/^component: //p' "$2" | sort | comm -13 "$3" -)
        [ -n "$list" ] || return 0
        printf '\n# %s\n\n' "$1"
        for c in $list; do
            printf '## %s\n\n' "$c"
            printf '| Property | Type |\n| --- | --- |\n'
            sed -n "s/^property: $c //p" "$2" |
                while read -r name ty; do printf '| `%s` | %s |\n' "$name" "$ty"; done
            events=$(sed -n "s/^event: $c //p" "$2" | sed 's/^/`/; s/$/`/' | paste -sd', ')
            printf '\n**Events:** %s\n\n' "${events:-none}"
        done
    }

    : > /tmp/kiln-empty.$$
    "$KILN" commands > /tmp/kiln-core-all.$$
    emit_components "Core" /tmp/kiln-core-all.$$ /tmp/kiln-empty.$$
    for l in "${LIBS[@]}"; do
        "$KILN" commands --use "$l" > /tmp/kiln-lib-all.$$
        emit_components "$l" /tmp/kiln-lib-all.$$ /tmp/kiln-core-comps.$$
    done
    rm -f /tmp/kiln-core-comps.$$ /tmp/kiln-core-all.$$ /tmp/kiln-lib-all.$$ /tmp/kiln-empty.$$
} > "$OUT/reference-components.md"

# --- templates ------------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Project templates

`kiln new <template> <directory>` creates a project from one of these. Each
one compiles and runs as it stands.

MD
    printf '| Template | Builds | What you get |\n| --- | --- | --- |\n'
    "$KILN" templates | awk '
        /^template: / { split($0, a, " "); id=a[2]; target[id]=a[3]; order[++n]=id }
        /^name: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); name[id]=$0 }
        /^desc: /     { split($0, a, " "); id=a[2]; $1=""; $2=""; sub(/^  /,""); desc[id]=$0 }
        END { for (i=1; i<=n; i++) { id=order[i];
                printf "| `%s` | `%s` | %s |\n", id, target[id], desc[id] } }'
} > "$OUT/reference-templates.md"

# --- command line ---------------------------------------------------------
{
    echo "$banner"
    echo
    cat <<'MD'
# Command line

```text
MD
    "$KILN" --help 2>&1
    cat <<'MD'
```

## Building

`kiln build` compiles a module to a native artifact and `kiln run`
builds it and runs it straight away.

```sh
kiln build app.kiln                      # ./app
kiln build app.kiln -o build/app         # somewhere else
kiln build lib.kiln --target sharedlib   # a different artifact
kiln run app.kiln
```

`--target` overrides whatever the module declares, so one source can be built
as a program or as a library without editing it. See
[Build targets](./build-targets.md).

A build writes the binary and nothing else. The LLVM IR it hands `clang` is an
intermediate and is removed once the link is done — `--emit-ir` keeps it beside
the binary as `<out>.ll`, and `kiln emit` prints it without building at all.

## Debug information

A build carries a DWARF line table: which address in the built program came
from which line of your source. It is what a debugger needs to stop on a line
and to say where it stopped. It is on by default and absent from a
`--release` build, which strips it along with everything else a shipped
program does not need.

`kiln debug` reads it back:

```sh
kiln debug --dump-lines app        # the line table, one row per line
kiln debug --dump-subs app         # the subroutines and their extents
kiln debug --resolve app app.kiln:24  # where a breakpoint on line 24 goes
kiln debug --at app 0x400557       # which line an address is in
```

A line that runs nothing — a blank line, a comment — resolves to the next
line that does, which is what you meant. An address in the runtime or in the
C library reports `line: none`, because it is not your code.

This reads a program; it does not run one. Stepping and breakpoints are being
built on top of it.

## Installing

`kiln install` copies the tree it is run from — a release bundle, or a source
checkout you have built — to a prefix, and links the binaries into
`<prefix>/bin`:

```sh
kiln install                 # /usr/local, or ~/.local when that is not writable
kiln install --user          # the same as --prefix ~/.local
kiln install --prefix /opt   # anywhere
kiln install --dry-run       # print what it would write, write nothing
kiln install --force         # replace an existing <prefix>/lib/kiln
kiln install --editors       # and Kate's syntax definition
```

The tree is relocatable by construction: `kiln` finds its runtime by walking
up from its own executable, so `<prefix>/lib/kiln` is self-contained and
`<prefix>/bin` holds symlinks into it. That is also why uninstalling is
deleting that directory and those links — there is no database to keep in
step, and no post-install step to forget.

It refuses to install a tree into itself, and refuses to replace an existing
`<prefix>/lib/kiln` without `--force`. A prefix it cannot write says so and
names `--user` rather than failing with a permission error.

## Starting a project

```sh
kiln templates                # what you can create
kiln new gui-app my-app       # create it
kiln new gui-app my-app --name my_module
kiln new gui-app my-app --title "Inventory"
```

The module is named after the directory unless `--name` says otherwise;
characters that cannot appear in an identifier are replaced. The title — a
GUI form's caption — is "Untitled App" unless `--title` says otherwise: a
folder name makes a poor caption, and a person names a project the way they
name a document, once it is something.

## Finding out what exists

```sh
kiln commands                 # the core runtime
kiln commands --use file      # and what a library adds
```

## Reading a project from a tool

`kiln inspect <file.kiln>` is how Kiln Studio learns what a file holds;
it is the only reader of a project file, so a tool that wants the same
knowledge asks it rather than parsing the source. The output is one fact per
line, `kind: rest`, in file order:

| Line | Meaning |
| --- | --- |
| `module: <name>` | the module's name |
| `use: <lib>` | a `use` line |
| `sub: <name>` | a subroutine; `subsig: <name> (<params>) <ret>` follows when it takes or returns anything |
| `form: <name> span=<first>..<last>` | the form, and the 1-based lines its `form … end` block occupies |
| `component: <id> <type>` | a component inside the form |
| `modcomponent: <id> <type> span=<first>..<last>` | a component declared at module level — a `timer`, an `httpserver` — with the lines of its block |
| `prop: <id> <name> <value>` | a property of the form or of the component named by `<id>` |
| `handler: <id> <event> <sub>` | an event binding |

A `prop:` value is always on its one line: a newline in it is written `\n`, a
NUL `\0`, and a backslash `\\`; nothing else is escaped. A reader reverses
exactly those three. A `modcomponent:` without a `span=` is one the toolchain
could not place, and a tool that splices the file should treat it as not yet
written rather than guess.

`kiln commands` is read the same way. Beside each `component: <type>` line
is `kind: <type> visual` or `kind: <type> nonvisual`, and a `property:` line
whose editor is not the plain one its type implies is followed by
`editor: <type> <property> <hint>` — `color`, `file`, `font` or `multiline`.
New line kinds are added; the existing ones do not change shape, so a reader
that skips what it does not know keeps working.

## Kits

A kit is a support library plus what an IDE needs to present it. `kiln kits`
lists the ones resolution found, each with its version and where it came from —
`project` for a `kits/` directory beside your source, `user` for
`~/.kiln/kits/`, `bundled` for the ones shipped with the toolchain. The
first match of a name wins, in that order.

```sh
kiln kits                     # what is installed, and from where
kiln kit add ./mykit          # install a directory
kiln kit add mykit.tar.gz     # or a tarball
```

See [Kits](./kits.md).

## Editor support

`kiln lsp` speaks the Language Server Protocol over stdin and stdout. It is
not run by hand — an editor starts it. See
[Editors and the language server](./editors.md).
MD
} > "$OUT/cli.md"

echo "generated: reference-commands.md reference-components.md reference-templates.md cli.md"
