#pragma once
/* The handbook, inside Studio.
 *
 * PureBasic's help file is the part of that product people actually praise:
 * it is offline, it is one keystroke away, and F1 on a keyword opens that
 * keyword's page rather than a search box. This is that, over our own docs.
 *
 * The pages are the Markdown the bundle ships in `docs/src/`, rendered by
 * `markdown.h`. Nothing here holds a copy of the prose, and the command and
 * component references are generated by `tools/gen-docs.sh` from the toolchain
 * — so what Studio shows is what the compiler actually has, or the build is
 * broken and `tools/check-docs.sh` says so.
 *
 * Layout is the settings dialog's, for the reasons written there: the rail and
 * the body are the only scrolling panes, both carry a full sized scrollbar
 * block because RmlUi gives a scrollbar no default size and an unsized one
 * eats every click meant for the content under it, and nothing inside a
 * scrolling pane is absolutely positioned because RmlUi will not clip it.
 */
#ifndef KILN_DESIGNER_HELP_PAGE_H
#define KILN_DESIGNER_HELP_PAGE_H

#include <algorithm>
#include <sstream>
#include <string>
#include <vector>

#include "markdown.h"
#include "portable.h"
#include "settings_page.h"
#include "theme.h"

namespace kiln::designer::help_page {

/// One line of the table of contents. `page` is empty for a section label.
struct Entry {
    std::string page;
    std::string title;
    bool section = false;
};

/// A search hit: the page, the heading it sits under, and the matching line.
struct Hit {
    std::string page;
    std::string title;
    std::string anchor;
    std::string line;
};

/// Where the handbook lives, in a bundle or in the source tree. Same search
/// order as `asset_path`, and the same contract: "" when it is not there, and
/// every caller copes.
inline std::string docs_dir() {
    std::vector<std::string> roots;
    const std::string dir = kiln::sys::exe_dir();
    if (!dir.empty()) {
        roots.push_back(dir + "/../docs/src");      // bundle: bin/ -> ../docs/src
        roots.push_back(dir + "/../../docs-site/src"); // repo: designer/ -> ../docs-site/src
        roots.push_back(dir + "/docs/src");
    }
    roots.push_back("docs-site/src");
    roots.push_back("docs/src");
    for (const auto& r : roots)
        if (kiln::sys::readable(r + "/SUMMARY.md")) return r;
    return "";
}

/// The HTML book beside the Markdown, for "open in browser". Empty when the
/// bundle shipped without it, which is what the Help menu checks before
/// offering the entry.
inline std::string book_index() {
    const std::string src = docs_dir();
    if (src.empty()) return "";
    const std::string candidate = src + "/../book/index.html";
    if (kiln::sys::readable(candidate)) return kiln::sys::real_path(candidate);
    return "";
}

/// Parse `SUMMARY.md`. It is mdBook's own nested list, so the book and this
/// viewer read one table of contents rather than two that drift.
inline std::vector<Entry> toc(const std::string& dir) {
    std::vector<Entry> out;
    const std::string src = md::read_file(dir + "/SUMMARY.md");
    std::istringstream in(src);
    std::string line;
    while (std::getline(in, line)) {
        size_t i = line.find_first_not_of(" \t");
        if (i == std::string::npos) continue;
        const std::string body = line.substr(i);
        // "# Section"
        if (body[0] == '#') {
            Entry e;
            e.title = body.substr(body.find_first_not_of("# "));
            // mdBook requires SUMMARY.md to open with its own title. That is
            // the file's name, not a section of the book.
            if (e.title == "Summary") continue;
            e.section = true;
            out.push_back(e);
            continue;
        }
        // "- [Title](./page.md)" or "[Title](./page.md)" for the unlisted ones.
        const size_t open = body.find('[');
        const size_t close = body.find("](");
        const size_t end = body.find(')', close == std::string::npos ? 0 : close);
        if (open == std::string::npos || close == std::string::npos || end == std::string::npos) continue;
        Entry e;
        e.title = body.substr(open + 1, close - open - 1);
        std::string page = body.substr(close + 2, end - close - 2);
        if (page.rfind("./", 0) == 0) page = page.substr(2);
        const size_t dot = page.rfind(".md");
        if (dot != std::string::npos) page = page.substr(0, dot);
        e.page = page;
        out.push_back(e);
    }
    return out;
}

/// Case-insensitive substring search across every page in the table of
/// contents, in the order the book lists them. Whole-word matches sort first,
/// so searching `print_text` does not bury the command under every mention.
inline std::vector<Hit> search(const std::string& dir, const std::string& query, size_t limit = 60) {
    std::vector<Hit> exact, loose;
    if (query.size() < 2) return exact;
    std::string q = query;
    std::transform(q.begin(), q.end(), q.begin(), ::tolower);

    for (const Entry& e : toc(dir)) {
        if (e.page.empty()) continue;
        const std::string src = md::read_file(dir + "/" + e.page + ".md");
        if (src.empty()) continue;
        std::string heading;
        std::istringstream in(src);
        std::string line;
        while (std::getline(in, line)) {
            if (!line.empty() && line[0] == '#') {
                heading = line.substr(line.find_first_not_of("# "));
                continue;
            }
            std::string low = line;
            std::transform(low.begin(), low.end(), low.begin(), ::tolower);
            const size_t at = low.find(q);
            if (at == std::string::npos) continue;

            Hit h;
            h.page = e.page;
            h.title = e.title + (heading.empty() ? "" : " \xE2\x80\xBA " + md::plain(heading));
            h.anchor = heading.empty() ? "" : md::slug(md::plain(heading));
            h.line = md::plain(line);
            // A hit inside a table comes back as its row. The pipes are
            // layout, not prose, so they read as noise in a snippet.
            for (char& c : h.line) if (c == '|') c = ' ';
            while (!h.line.empty() && h.line.front() == ' ') h.line.erase(h.line.begin());
            while (!h.line.empty() && h.line.back() == ' ') h.line.pop_back();
            if (h.line.size() > 150) h.line = h.line.substr(0, 150) + "\xE2\x80\xA6";

            const bool bounded =
                (at == 0 || !std::isalnum(static_cast<unsigned char>(low[at - 1]))) &&
                (at + q.size() >= low.size() ||
                 !std::isalnum(static_cast<unsigned char>(low[at + q.size()])));
            (bounded ? exact : loose).push_back(h);
            if (exact.size() + loose.size() >= limit * 3) break;
        }
    }
    exact.insert(exact.end(), loose.begin(), loose.end());
    if (exact.size() > limit) exact.resize(limit);
    return exact;
}

/// Which page documents a command or a component, and the anchor within it.
/// The reference is a table per library with one row per name, and the
/// renderer stamps `cmd-<name>` on each row — so this is a lookup, not a scan
/// of the prose.
inline bool lookup(const std::string& dir, const std::string& name,
                   std::string* page, std::string* anchor) {
    for (const char* p : {"reference-commands", "reference-components"}) {
        const std::string src = md::read_file(dir + "/" + p + ".md");
        // A documented command has its own entry — what it does and a program
        // that calls it — and that is where F1 should land. An undocumented
        // one has only its row in the index, so land on the row.
        if (src.find("\n### `" + name + "`") != std::string::npos) {
            *page = p;
            *anchor = name;
            return true;
        }
        // The index cell is a link once the command has an entry, so both
        // shapes have to be recognised.
        if (src.find("| `" + name + "` |") != std::string::npos ||
            src.find("| [`" + name + "`](#") != std::string::npos) {
            *page = p;
            *anchor = "cmd-" + name;
            return true;
        }
    }
    return false;
}

constexpr int RAIL_W = 210;
constexpr int HEAD_H = 46;
constexpr int MARGIN = 40;

/// The whole document, for a window `w` x `h`.
///
/// When `query` is set the body is the result list; otherwise it is `page`,
/// rendered. One document either way, so there is one close path and one
/// listener rather than two of each.
inline std::string markup(const std::string& family, const std::string& mono, int w, int h,
                          const std::string& dir, const std::string& page,
                          const std::string& query, std::vector<std::string>* code = nullptr) {
    using namespace kiln::designer::theme;

    const int dlg_w = std::min(1120, w - MARGIN * 2 > 320 ? w - MARGIN * 2 : 320);
    const int dlg_h = std::min(820, h - MARGIN * 2 > 240 ? h - MARGIN * 2 : 240);
    const int left = (w - dlg_w) / 2 > 0 ? (w - dlg_w) / 2 : 0;
    const int top = (h - dlg_h) / 2 > 0 ? (h - dlg_h) / 2 : 0;
    const int body_w = dlg_w - RAIL_W;
    const int body_h = dlg_h - HEAD_H;
    // The pane's width, less its padding, less the scrollbar. A reference page
    // is always long enough to scroll, and the scrollbar takes its width out of
    // the content — table columns sized without allowing for it wrap every row.
    const int content_w = body_w - 56 - 14;

    std::ostringstream s;
    s << "<rml><head><style>";
    s << "div{display:block}span{display:inline}img{display:block}";
    // The body is the click-outside target, so it must fill the window: an
    // unsized body is 0x0 and no click ever lands on it.
    s << "body{position:absolute;left:0;top:0;width:" << w << "px;height:" << h << "px;font-family:'"
      << family << "';font-size:12px;color:" << TEXT << ";background-color:#0000002e}";
    s << "#dlg{position:absolute;left:" << left << "px;top:" << top << "px;width:" << dlg_w
      << "px;height:" << dlg_h << "px;background-color:" << PANEL << ";border:1px " << BORDER
      << ";border-radius:12px;box-shadow:#00000044 0 16px 48px 0px}";

    s << "#head{position:absolute;left:0;top:0;width:" << dlg_w << "px;height:" << HEAD_H
      << "px;border-bottom:1px " << BORDER_SOFT << "}";
    s << "#title{position:absolute;left:18px;top:15px;font-size:13px;font-weight:bold;color:"
      << TEXT << "}";
    s << "#find{position:absolute;right:46px;top:11px;width:230px;height:24px;border:1px "
      << BORDER << ";border-radius:12px;background-color:" << CHROME_ALT << ";color:" << TEXT
      << ";padding-left:10px;font-size:12px}";
    s << "#find:focus{border:1px " << ACCENT << "}";
    // Explicitly sized. An absolutely positioned block given `right` and no
    // width takes the whole bar and paints over the search field.
    s << "#browser{position:absolute;right:296px;top:15px;width:104px;text-align:right;"
         "font-size:11px;color:" << TEXT_MUTED << ";cursor:pointer}";
    s << "#browser:hover{color:" << ACCENT << "}";
    s << "#x{position:absolute;right:12px;top:11px;width:24px;height:24px;text-align:center;"
         "padding-top:3px;font-size:13px;color:" << TEXT_MUTED << ";border-radius:4px;cursor:pointer}";
    s << "#x:hover{background-color:" << CHROME << ";color:" << TEXT << "}";

    s << "#rail{position:absolute;left:0;top:" << HEAD_H << "px;width:" << RAIL_W << "px;height:"
      << body_h << "px;background-color:" << CHROME_ALT << ";border-right:1px " << BORDER_SOFT
      << ";padding:10px 0 10px 0;overflow-y:auto}";
    s << "#rail .sec{padding:12px 10px 4px 14px;font-size:10px;font-weight:bold;color:"
      << TEXT_MUTED << "}";
    s << "#rail .pg{padding:5px 10px 5px 18px;font-size:12px;color:" << TEXT << ";cursor:pointer}";
    s << "#rail .pg:hover{background-color:" << CHROME << "}";
    s << "#rail .pg.on{background-color:" << ACCENT << ";color:" << ACCENT_TEXT
      << ";font-weight:bold}";

    // Width is the pane minus its own padding: RmlUi's box model is
    // content-box, so a full-width pane with padding hangs over the dialog's
    // right edge and takes its scrollbar with it, off-screen.
    s << "#body{position:absolute;left:" << RAIL_W << "px;top:" << HEAD_H << "px;width:"
      << (body_w - 56) << "px;height:" << (body_h - 46)
      << "px;padding:18px 28px 28px 28px;overflow-y:auto}";

    // Sized, because RmlUi gives a scrollbar no default size and an unsized one
    // covers its owner and eats every click. This has broken Studio twice.
    s << "scrollbarvertical{width:10px}";
    s << "scrollbarhorizontal{height:10px}";
    s << "slidertrack{background-color:" << CHROME_ALT << "}";
    s << "sliderbar{width:10px;min-height:24px;border-radius:5px;background-color:" << BORDER << "}";
    s << "sliderbar:hover{background-color:" << TEXT_MUTED << "}";
    s << "sliderarrowdec,sliderarrowinc{width:0px;height:0px}";

    // The rendered page.
    s << ".mdh1{font-size:21px;font-weight:bold;color:" << TEXT << ";margin:6px 0 14px 0}";
    s << ".mdh2{font-size:16px;font-weight:bold;color:" << TEXT << ";margin:22px 0 9px 0;"
         "padding-bottom:5px;border-bottom:1px " << BORDER_SOFT << "}";
    s << ".mdh3{font-size:13px;font-weight:bold;color:" << TEXT << ";margin:18px 0 7px 0}";
    s << ".mdh4{font-size:12px;font-weight:bold;color:" << TEXT_MUTED << ";margin:14px 0 6px 0}";
    s << ".mdp{font-size:12px;color:" << TEXT << ";line-height:1.55;margin-bottom:11px}";
    s << ".mdb{font-weight:bold}";
    s << ".mdi{font-style:italic;color:" << TEXT_MUTED << "}";
    s << ".mdcode{font-family:'" << mono << "';font-size:11px;color:" << ACCENT
      << ";background-color:" << CHROME_ALT << ";border-radius:3px;padding:1px 4px 1px 4px}";
    s << ".mdlink{color:" << ACCENT << ";cursor:pointer}";
    s << ".mdlink:hover{text-decoration:underline}";
    s << ".mdpre{background-color:" << CHROME_ALT << ";border:1px " << BORDER_SOFT
      << ";border-radius:6px;padding:8px 12px 10px 12px;margin-bottom:13px}";
    s << ".mdcopyrow{text-align:right;margin-bottom:4px}";
    s << ".mdcopy{display:inline-block;font-size:10px;color:" << TEXT_MUTED
      << ";background-color:" << PANEL << ";border:1px " << BORDER_SOFT
      << ";border-radius:4px;padding:2px 7px 2px 7px;cursor:pointer}";
    s << ".mdcopy:hover{color:" << ACCENT << ";border:1px " << ACCENT << "}";
    s << ".mdcodeline{font-family:'" << mono << "';font-size:11px;line-height:1.45;white-space:nowrap}";
    s << ".mdrule{height:1px;background-color:" << BORDER_SOFT << ";margin:18px 0 18px 0}";
    s << ".mdli{margin-bottom:5px;font-size:12px;line-height:1.5}";
    s << ".mdbullet{color:" << ACCENT << ";margin-right:8px}";
    s << ".mdimg{margin:6px 0 14px 0;width:" << (content_w - 8) << "px}";
    s << ".mdrow{padding:5px 0 5px 0;border-bottom:1px " << BORDER_SOFT << "}";
    s << ".mdrow.mdhead{font-weight:bold;color:" << TEXT_MUTED << ";font-size:11px;"
         "border-bottom:1px " << BORDER << "}";
    s << ".mdrow.hit{background-color:" << CHROME << "}";
    s << ".mdcell{display:inline-block;font-size:12px;vertical-align:top;padding-right:8px}";
    // A result row.
    s << ".res{padding:9px 10px 9px 10px;margin-bottom:4px;border-radius:6px;cursor:pointer;"
         "border:1px transparent}";
    s << ".res:hover{background-color:" << CHROME_ALT << ";border:1px " << BORDER_SOFT << "}";
    s << ".res .where{font-size:11px;font-weight:bold;color:" << ACCENT << "}";
    s << ".res .what{font-size:11px;color:" << TEXT_MUTED << ";margin-top:3px;line-height:1.45}";
    s << ".empty{font-size:12px;color:" << TEXT_MUTED << ";margin-top:20px}";

    s << "</style></head><body id='help-bg'>";
    s << "<div id='dlg'>";
    s << "<div id='head'><div id='title'>Documentation</div>";
    s << "<input type='text' id='find' value='" << settings_page::esc_attr(query)
      << "' placeholder='Search the handbook'/>";
    if (!book_index().empty())
        s << "<div id='browser' oe-help='browser'>Open in browser</div>";
    s << "<div id='x' oe-help='close'>\xE2\x9C\x95</div></div>";

    // The rail.
    s << "<div id='rail'>";
    for (const Entry& e : toc(dir)) {
        if (e.section) { s << "<div class='sec'>" << escape_rml(e.title) << "</div>"; continue; }
        s << "<div class='pg" << (e.page == page && query.empty() ? " on" : "")
          << "' oe-help-page='" << escape_rml(e.page) << "'>" << escape_rml(e.title) << "</div>";
    }
    s << "</div>";

    // The body.
    s << "<div id='body'>";
    if (code) code->clear();
    if (!query.empty()) {
        const std::vector<Hit> hits = search(dir, query);
        s << "<div class='mdh1'>" << escape_rml(std::to_string(hits.size()))
          << (hits.size() == 1 ? " result for " : " results for ") << "\xE2\x80\x9C"
          << escape_rml(query) << "\xE2\x80\x9D</div>";
        if (hits.empty())
            s << "<div class='empty'>Nothing in the handbook matches. Try a command name, or a "
                 "word from the language guide.</div>";
        for (const Hit& hit : hits) {
            s << "<div class='res' oe-help-page='" << escape_rml(hit.page)
              << "' oe-help-anchor='" << escape_rml(hit.anchor) << "'>";
            s << "<div class='where'>" << escape_rml(hit.title) << "</div>";
            s << "<div class='what'>" << escape_rml(hit.line) << "</div></div>";
        }
    } else {
        const std::string src = md::read_file(dir + "/" + page + ".md");
        if (src.empty()) {
            s << "<div class='mdh1'>Not found</div><div class='empty'>The handbook has no page "
                 "named " << escape_rml(page) << ".</div>";
        } else {
            const md::Doc doc = md::render(src, content_w, dir);
            s << doc.rml;
            // The page's code blocks, so a copy button can find its own.
            if (code) *code = doc.code;
        }
    }
    s << "</div></div></body></rml>";
    return s.str();
}

} // namespace kiln::designer::help_page

#endif
